# Generated by Django 3.2.10 on 2021-12-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20211219_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
