# Generated by Django 3.2.10 on 2021-12-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_sessionyearmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
    ]
