# Generated by Django 3.2.10 on 2021-12-19 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_alter_sessionyearmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
